### ISSUE TITLE
osvr_server crashed when load com_osvr_Vive.dll

### ISSUE THREAD

**Issue by smallccn** [OSVR/OSVR-Vive#25] opened 2017-01-10 13:34 UTC
Hello,

I meet an issue that osvr_server will always crashed when load com_osvr_Vive.dll(Both the version I build and download from the offical link have this issue).

I've added some debug code and find that it will be always crash at below code.
//DriverWrapper.h
        /// This method must be called before calling
        /// startServerDeviceProvider()
        bool isHMDPresent() {
            if (!(foundDriver() && foundConfigDirs() && haveDriverLoaded())) {
                return false;
            }
            if (!loader_) {             <--- always crash at here.
                throw std::logic_error("Calls to isHMDPresent must occur "
                                       "before startServerDeviceProvider!");
            }
            return loader_->isHMDPresent(locations_.rootConfigDir);
        }

I don't know why it will be crash at here, actually I don't do anything, and I also think this maybe caused by the latest version of driver_lighthouse.dll(my version date is 2017.01.04), but I can't find an old version to verify it. 

Is there anyone can help to check this issue?

Thanks.

**Comment by mars979** [comment] 2017-05-11 14:57
Hello @smallccn ,
The errors were occurring because OpenVR released a new API with breaking changes and the previous version of the plugin was not compatible with new lighthouse driver.
We updated the plugin and merged the code into master and you can download the latest binaries from [here](http://access.osvr.com/binary/vive) that work with latest lighthouse drivers or build it from source and try it out.
Let us know if your problem is resolved with the latest plugin version.

-Georgiy

**Comment by tanjaU29798** [comment] 2017-06-06 13:42
Hello :)
I have a similar problem with my build... Starting the osvr_server of the SDK (C:\Program Files (x86)\OSVR\SDK\x86\bin) gives me the following code before crashing:

June 06 15:02:05.991 info [OSVR]: Logging for C:\Program Files (x86)\OSVR\SDK\x86\bin\osvr_server.exe
June 06 15:02:05.992 info [OSVR Server]: Using default config file - pass a filename on the command line to use a different one.
June 06 15:02:05.992 info [OSVR Server]: Using config file 'osvr_server_config.json'.
June 06 15:02:05.992 info [OSVR Server]: Constructing server as configured...
June 06 15:02:05.997 info [OSVR Server]: Loading auto-loadable plugins...
June 06 15:02:06.021 info [OSVR]: Logging for C:\Program Files (x86)\OSVR\SDK\x86\bin\osvr_server.exe

The Runtime (C:\Program Files (x86)\OSVR\Runtime\bin) doesn't crash but can't load the plugin:

June 06 15:04:41.958 info [OSVR]: Logging for C:\Program Files (x86)\OSVR\Runtime\bin\osvr_server.exe
June 06 15:04:41.959 info [OSVR Server]: Using default config file - pass a filename on the command line to use a different one.
June 06 15:04:41.959 info [OSVR Server]: Using config file 'osvr_server_config.json'.
June 06 15:04:41.959 info [OSVR Server]: Constructing server as configured...
June 06 15:04:41.964 info [OSVR Server]: Loading auto-loadable plugins...
June 06 15:04:41.973 warning [PluginHost]: Failed to load plugin com_osvr_Vive: Failed to load the module C:/Program Files (x86)/OSVR/Runtime/bin/osvr-plugins-0/com_osvr_Vive
June 06 15:04:41.976 info [OSVR Server]: Loading plugins...
June 06 15:04:41.977 info [OSVR Server]: Instantiating configured drivers...
June 06 15:04:41.977 info [OSVR Server]: Added device: org_osvr_filter_videoimufusion/HeadFusion
[...]

Since both servers are working correctly with the prebuild Version (OSVR-Vive-build69-32bits) something has to be wrong with my building process... 
I never worked with osvr, vs2013 and cmake before so maybe my error is obvious to you. 


![cmake](https://cloud.githubusercontent.com/assets/22773825/26831979/467ac19e-4ace-11e7-89e0-31e3acd33434.PNG)


From vs2013 I get:

[...]
2>C:\Users\prouser\Desktop\u29798\viveRecursive\Properties.cpp(161): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
2>C:\Users\prouser\Desktop\u29798\viveRecursive\Properties.cpp(192): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
2>C:\Users\prouser\Desktop\u29798\viveRecursive\Properties.cpp(313): warning C4244: 'argument' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
[...]
8>------ Skipped Rebuild All: Project: INSTALL, Configuration: Release Win32 ------
8>Project not selected to build for this solution configuration 
========== Rebuild All: 7 succeeded, 0 failed, 1 skipped ==========

Should I try different versions of Boost/Eigen/opencv? Or did I do something wrong with cmake?
Thank you a lot for your help :)

**Comment by mars979** [comment] 2017-06-20 20:16
@smallccn ,
Please try the latest OSVR-Vive plugin (also available on `http://access.osvr.com/binary/vive`) which fixes the crashing error that you were seeing with an earlier version of the plugin.

If the issue is resolved for you, then please go ahead and close the issue. Feel free to let us know if you're still encountering the crash.

**Comment by gfrolov** [comment] 2017-12-11 15:33
The crash issue was related to breaking changes in OpenVR API, and the plugin has been updated to the latest version. Closing this issue.

**Closed by gfrolov** 2017-12-11 15:33 UTC
